name: Prepare Plugin Release

on:
  push:
    branches: ["main"]

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Plugin Version
        id: get_version
        run: |
          version=$(grep -i "Version:" leadtrackr.php | awk -F' ' '{print $NF}')
          echo "PLUGIN_VERSION=$version" >> $GITHUB_ENV

      - name: Strip files and directories
        run: rm -rf .git .github

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
    
      - name: Install dependencies
        run: cd app && npm install

      - name: Build Vite React app
        run: cd app && npm run build

      - run: mkdir leadtrackr-release
      - run: cp leadtrackr.php leadtrackr-release/
      - run: mkdir leadtrackr-release/app
      - run: cp -r app/dist leadtrackr-release/app
      - run: cp -r assets leadtrackr-release/

      - name: Create zip
        run: cd leadtrackr-release && zip -r leadtrackr.zip ./* && mv leadtrackr.zip ../

      - name: Create Draft Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "leadtrackr.zip"
          draft: true
          name: "Draft Release v${{ env.PLUGIN_VERSION }}"
          tag: v${{ env.PLUGIN_VERSION }}
